name: 'uberides'
version: '1.0'
config-version: 2

profile: 'uberides'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

quoting:
  schema: false   # prevents dbt from appending project name into schema names

models:
  uberides:
    staging:      
      +materialized: view
    marts:      
      +materialized: table
    sources:
      +schema: raw_ext
      +materialized: view