name: uberides-weekly

on:
  workflow_dispatch:
  # schedule:
  #   # Friday 20:05 Phoenix ~= Saturday 03:05 UTC
  #   - cron: "5 3 * * 6"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AZURE_UBERRIDES_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_UBERRIDES_STORAGE_CONNECTION_STRING }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ---- OPTIONAL STATE RESTORE (non-fatal on first run) ----
      - name: Try restore previous state artifact
        id: try-restore
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: uberides-state
          path: .
      - name: Show state presence
        run: |
          ls -la . || true
          [ -f .uberides.env ] && echo "Found .uberides.env" || echo "No state file yet (first run is OK)"

      # ---- RUN DAGSTER JOB ----
      - name: Run weekly generator
        run: |
          python - <<'PY'
          from dagster_repo import uberides_weekly_job
          result = uberides_weekly_job.execute_in_process()
          if not result.success:
              raise SystemExit("Dagster job failed")
          PY

      # ---- UPLOAD/REFRESH STATE FOR NEXT RUN ----
      - name: Upload state (only if file exists)
        if: ${{ hashFiles('.uberides.env') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: uberides-state
          path: ./.uberides.env
          if-no-files-found: ignore
